### ISSUE TITLE
Ссылки на полезные материалы указаны неправильно

### ISSUE THREAD

**Issue by MarianCompany** [slavaver/web-course-site#38]
https://slavaver.github.io/web-course-site/useful/
В ссылке на каждый материал указан лишний "useful" - https://slavaver.github.io/web-course-site/useful**/useful**/hide-element

**Comment by slavaver** [comment]
Исправлено в комите - [fix link in useful](https://github.com/slavaver/web-course-site/commit/f2cdf2b7153761df9236618d00efd8563193dea4)
